# Default values for deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# to reset password: htpasswd -s -b -n internal changeme
openshift_prometheus_htpasswd_auth: internal:{SHA}+pvrmeQCmtWmYVOZ57uuITVghrM=
openshift_prometheus_basic_auth_pass: changeme
extra_prometheus_hosts:

# Uncomment this if your cluster serves privately signed certificates
# custom_ca: true

deployment:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: pelorus
    app.kubernetes.io/version: v0.33.0

exporters:
  instances:
    # Values file for exporter helm chart
  - app_name: deploytime-exporter
    source_context_dir: exporters/
    extraEnv:
    - name: APP_FILE
      value: deploytime/app.py
    - name: LOG_LEVEL
      value: DEBUG
    source_ref: master
    source_url: https://github.com/konveyor/pelorus.git
  - app_name: committime-generic
    env_from_secrets:
    - github-secret
    - mongodb-build-webhook
    source_context_dir: exporters/
    extraEnv:
    - name: APP_FILE
      value: committime/app.py
    - name: LOG_LEVEL
      value: DEBUG
    - name: PROVIDER
      value: "webhook"
    source_ref: master
    source_url: https://github.com/konveyor/pelorus.git

webhooks:
  instances:
  - app_name: build-webhook
    source_context_dir: webhooks/
    extraEnv:
    - name: APP_FILE
      value: build-webhook/app.py
    - name: LOG_LEVEL
      value: DEBUG
    source_ref: master
    source_url: https://github.com/konveyor/pelorus.git
    mongodb:
      namespace: openshift
      imagestream: "mongodb:3.6"
      memory_limit: 512Mi

snapshot_schedule: "@monthly"
