{{- define "mongodb.secret" }}
{{- range $index, $webhook := $.Values.instances }}
{{- $mongoAdminPasswd := (randAlphaNum 10) | quote }}
{{- $mongoPasswd := (randAlphaNum 10) | quote }}
{{- $mongoUser := (randAlpha 10) | quote }}
{{- $appName := printf "mongodb-%s" .app_name }}
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace $appName) }}
{{- if $secret }}
{{- $mongoAdminPasswd = $secret.data.MONGODB_ADMIN_PASSWORD | b64dec | quote }}
{{- $mongoPasswd = $secret.data.MONGODB_PASSWORD | b64dec | quote }}
{{- $mongoUser = $secret.data.MONGODB_USER | b64dec | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: "mongodb-{{ .app_name }}"
  name: "mongodb-{{ .app_name }}"
stringData:
  MONGODB_ADMIN_PASSWORD: {{ $mongoAdminPasswd }}
  MONGODB_DATABASE: "mongodb-{{ .app_name }}"
  MONGODB_PASSWORD: {{ $mongoPasswd }}
  MONGODB_USER: {{ $mongoUser }}
  MONGODB_SERVICE_HOST: "mongodb-{{ .app_name }}"
{{- end }}
{{- end }}
