{{- define "mongodb.service" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: "mongodb-{{ .app_name }}"
  name: "mongodb-{{ .app_name }}"
spec:
  ports:
  - name: http
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: "mongodb-{{ .app_name }}"
  type: ClusterIP
{{- end }}
