name: Conftest

on: [push, pull_request]

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.2

      - name: Update dep charts
        run: helm dep update charts/pelorus

      - name: Conftest
        uses: redhat-cop/github-actions/confbatstest@master
        with:
          tests: _test/conftest.sh
